sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t9UKBmdh1XbDNdJvijk
    access-key-secret: f0h2LElbtaoh6wC4116iCnMnUwbV0o
    bucket-name: javaboyhh

  redis:
    host: localhost
    port: 6379

  wechat:
    appid: wx22b362c211ad180f
    secret: 098f48c47cd365431e874e6ac79a89b8